<%@ Page Title="" Language="C#" MasterPageFile="~/executive.Master" AutoEventWireup="true" CodeBehind="searchrecord.aspx.cs" Inherits="Police_Investigation_System_NEW_.searchrecord" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <center>
     <style type="text/css">
        body
        {
            font-family: Arial;
            font-size: 10pt;
        }
        table
        {
            border: 1px solid #ccc;
            border-collapse: collapse;
            background-color: #fff;
        }
        table th
        {
            background-color: #B8DBFD;
            color: #333;
            font-weight: bold;
        }
        table th, table td
        {
            padding: 5px;
            border: 1px solid #ccc;
        }
        table, table table td
        {
            border: 0px solid #ccc;
        }
    </style>

   
    <asp:GridView ID="GridView1" runat="server" DataKeyNames="Caseno" OnRowDataBound="OnRowDataBound"
        OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating"
        OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateEditButton="true"
        ShowHeaderWhenEmpty="true" AutoGenerateDeleteButton="true">
    </asp:GridView>
   
 
        </center>

</asp:Content>
